Feature/count ops on specified qubits
Qiskit/qiskit-terra pull request #10257
Opened 2023-06-12 00:13 UTC by HaoranLiao

### Summary
By default, `QuantumCircuit.count_ops()` returns counts of existing operations on all qubits. Added support to count existing operations on specified qubit(s). E.g., `QuantumCircuit.count_ops(qubits=[1, 2])` counts any operations involving qubits 1 and 2 in the circuit. 

### Details and comments
It returns the counts of any operations that operate on the specified qubits.

2023-06-12 00:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=10257) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit?pullRequest=10257) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: HaoranLiao<br/>:x: Haoran Liao<br/><hr/>**Haoran Liao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit?pullRequest=10257) it.</sub>

2023-06-13 04:56 UTC, alexanderivrii commented on qiskit/circuit/quantumcircuit.py
> +                        count_ops[instruction.operation.name] = count_ops.get(instruction.operation.name, 0) + 1
if qubits=[1,2], wouldn't a CX(1, 2)-gate be counted twice?

2023-07-01 08:04 UTC, atharva-satpute commented on releasenotes/notes/add_count_ops_on_qubits_support-84f9a49aaa97f1cc.yaml
> +    Added support for couting operations on specified qubit(s) in :meth:`~qiskit.circuit.quantumcircuit.count_ops`.
```suggestion
    Added support for counting operations on specified qubit(s) in :meth:`~qiskit.circuit.quantumcircuit.count_ops`.
```

2023-07-01 08:05 UTC, atharva-satpute requested changes
Please fix the typo

2023-07-01 08:05 UTC, atharva-satpute commented on releasenotes/notes/add_count_ops_on_qubits_support-84f9a49aaa97f1cc.yaml
> +    Added support for couting operations on specified qubit(s) in :meth:`~qiskit.circuit.quantumcircuit.count_ops`.
```suggestion
    Added support for counting operations on specified qubit(s) in :meth:`~qiskit.circuit.quantumcircuit.count_ops`.
```

2026-01-15 01:14 UTC, jakelishman commented
Closing as stale

2026-01-15 01:14 UTC, closed without merging