Fixed issue 3615 by updating schedule.filter() to accept scalar values as well as iterables
Qiskit/qiskit-terra pull request #3646
Opened 2019-12-22 01:19 UTC by NuoWenLei

### Summary

Fixes #3615 

### Details and comments

In construct_filter:
Using try/except detecting TypeError for all parameters except channel, it can now pass scalar values as well as iterables

For Channel - in schedule.filter():
Passing only one channel resulted in no filter whatsoever in terms of channel, therefore in schedule.filter() when one channel is passed, the exact same channel is added to create an iterable for construct_filter().

2019-12-22 01:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=3646) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=3646) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=3646) it.</sub>

2019-12-22 01:20 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=3646) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=3646) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=3646) it.</sub>

2019-12-22 02:45 UTC, NuoWenLei commented
Hi, what should I do with the 2 checks that did not pass? And is there any way to look closer as to where the errors occurred?

2019-12-30 13:48 UTC, ajavadia commented
@NuoWenLei you can see the error by clicking on "Details" and then the red crosses.
In this case it says:

> qiskit/pulse/schedule.py:18:0: W0611: Unused Set imported from typing (unused-import)

2020-01-07 21:21 UTC, taalexander reviewed
Withing `_construct_filter` could you define a method `scalar_to_list` and just call that on the arguments of the generator methods

```python
def if_scalar_cast_to_list(input)
try:
    iter(input)
except TypeError, te:
    input = list(input)
return input
```
You would also have to create a`time_ranges` generator function and remove the set cast from channels. This may be the cleanest approach.

2020-01-11 19:32 UTC, NuoWenLei commented
Hello, I have a question regarding my local qiskit. I've made the requested changes and I'm hoping to test it out with jupyter notebook. However, it seems that one of my files in qiskit-terra is messed up, and so it would not run. Is there any way of updating my local qiskit-terra branch without needing to make a pull request for all the new files? Sorry for such a simple question.

2020-01-16 19:19 UTC, NuoWenLei commented
Ok, I'm working on it!

2020-01-21 22:31 UTC, NuoWenLei commented
I've made the changes, how do I update the pull request?

2020-01-30 02:42 UTC, NuoWenLei commented
This new pull request has the function asked by #3615

2020-02-03 15:50 UTC, taalexander requested changes
This looks much better! Couple of small suggestions.

2020-02-03 15:50 UTC, taalexander commented on qiskit/pulse/schedule.py
> +        if channels is not None:
Is there a reason the logic is here and not `_construct_filter`?

2020-02-03 15:50 UTC, taalexander commented on qiskit/pulse/schedule.py
> +        def only_channels(channels: Channel) -> Callable:
I believe this is still accepting an iterable? Should this be a type of `Union[Set[Channel], Channel]`.

2020-02-03 15:50 UTC, taalexander commented on qiskit/pulse/schedule.py
> +        def only_instruction_types(types: Optional[Iterable[abc.ABCMeta]] = None) -> Callable:
Should this type be `Union[abc.ABCMeta, Iterable[abc.ABCMeta]]`

2020-02-03 15:50 UTC, taalexander commented on qiskit/pulse/schedule.py
> +        def only_intervals(ranges: Interval) -> Callable:
Similar union type update here.

2020-02-03 15:50 UTC, taalexander commented on qiskit/pulse/schedule.py
> +                try:
It seems we have the iterable check code here and down below prior to calling this on line 372. Is there a reason for this?

2020-02-18 22:28 UTC, NuoWenLei commented
Hi, I updated the union parameters in #3768 .

2020-02-26 15:26 UTC, taalexander commented
Hello @NuoWenLei, could you please help me understand the difference between this PR and #3768?

2020-02-26 18:20 UTC, NuoWenLei commented
Hi, sorry for the extra PR, I couldn't figure out how to update the changed code for this PR, so instead I created another PR and referenced this one. #3768 has the most recent and most complete patches.

2020-03-13 13:48 UTC, taalexander commented
Ok, in that case, I will close this PR and review your other PR 😄.

2020-03-13 13:48 UTC, closed without merging

2024-05-05 21:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=3646) <br/>All committers have signed the CLA.

2026-04-21 03:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=3646) <br/>All committers have signed the CLA.