Add qasm rep delay
Qiskit/qiskit-terra pull request #5048
Opened 2020-09-09 01:09 UTC by zachschoenfeld33

## Summary

Add `rep_delay` in QASM path, analogous to pulse.

### Details and comments
- Can now specify `rep_delay` in QASM qobj
- backend rep delay flags (`dynamic_reprate_enabled`, `default_rep_delay`, `rep_delay_range`) now included in `QasmBackendConfiguration`

2020-09-09 19:01 UTC, lcapelluto submitted a review, later dismissed
LGTM.

2020-09-09 21:28 UTC, zachschoenfeld33 commented on qiskit/providers/models/backendconfiguration.py
> +    Inherits from Qasm backend configuration.
Addressed in https://github.com/Qiskit/qiskit-terra/pull/5048/commits/6e1bc7c296dd5928c2b6008b8e093c9b9df2dd32.

2020-09-10 14:35 UTC, taalexander requested changes

2020-09-10 14:43 UTC, zachschoenfeld33 commented on qiskit/qobj/qasm_qobj.py
> +            rep_delay (float): Delay between programs in sec. Only supported on certain
Addressed in https://github.com/Qiskit/qiskit-terra/pull/5048/commits/37f21b73c1844f3d991ed3f57bd4dee89627832d.

2020-09-10 15:39 UTC, taalexander submitted a review, later dismissed

2020-09-11 15:46 UTC, zachschoenfeld33 commented
Added in https://github.com/Qiskit/qiskit-terra/pull/5048/commits/cc649b2579e79ba6146a1fab0eab732ed805b0e5 fix for issue cited by @ajavadia where warning occurs for dynamic rep rate not on even when `rep_delay` is not entered in assemble.

2020-09-15 17:25 UTC, taalexander requested changes

2020-09-15 17:25 UTC, taalexander commented on qiskit/schemas/backend_configuration_schema.json
>                          "type": "string",
The schema version needs a minor bump.

2020-09-15 17:25 UTC, taalexander commented on qiskit/schemas/qobj_schema.json
>                          "pulse_library": {
Schema needs a minor version bump.

2020-09-15 18:00 UTC, taalexander approved these changes

2020-09-15 18:44 UTC, merged