circuit.draw display when ipython
Qiskit/qiskit-terra pull request #5328
Opened 2020-10-30 21:10 UTC by 1ucian0

Thanks to @frankharkins, I learned about `IPython.display.display`. This allows circuit to be drew circuits in a loop.

Take the following example:
```python
from qiskit import QuantumCircuit
qc1 = QuantumCircuit(2)
qc1.h(0)
qc1.cx(0,1)

qc2 = QuantumCircuit(2)
qc2.h(1)
qc2.cx(1,0)

circuits = [qc1, qc2]
``` 

These are the outputs:
<img width="317" alt="Screen Shot 2020-10-30 at 5 08 52 PM" src="https://user-images.githubusercontent.com/766693/97757228-b5c56900-1ad2-11eb-9870-78c2cc4d1c71.png">
<img width="363" alt="Screen Shot 2020-10-30 at 5 09 00 PM" src="https://user-images.githubusercontent.com/766693/97757237-b8c05980-1ad2-11eb-9ede-835fa1a5877f.png">
<img width="431" alt="Screen Shot 2020-10-30 at 5 09 07 PM" src="https://user-images.githubusercontent.com/766693/97757251-bd850d80-1ad2-11eb-9448-4fcc7063dc70.png">
<img width="439" alt="Screen Shot 2020-10-30 at 5 09 16 PM" src="https://user-images.githubusercontent.com/766693/97757254-bf4ed100-1ad2-11eb-885c-dc25cbd61eb9.png">

This makes #5030 unnecessary, so removing.

2020-11-04 09:57 UTC, frankharkins commented
I think this would cause confusing behaviour. For example, in Jupyter Notebooks we wouldn't be able to do `qc.draw().savefig()`, but this would be fine in a script.

I would suggest leaving the `.draw()` functionality as is, and instead adding an `_ipython_display_` method to the `QuantumCircuit` class. Then if someone wants to view their circuit they can type `display(qc)`, or just `qc` if it's the last line of a cell. Slowly over time we can encourage the behaviour of using `display(<object>)` to show something in a notebook, and `.draw()` when we want to do something with that drawing.

2020-11-05 02:13 UTC, 1ucian0 commented
> I think this would cause confusing behaviour. For example, in Jupyter Notebooks we wouldn't be able to do `qc.draw('mpl').savefig()`, but this would be fine in a script.

What about `qc.draw(..., display=True)`?

2020-11-05 12:28 UTC, frankharkins commented
> What about `qc.draw(..., display=True)`?

This is better, but notebook users typing `qc.draw(display=True)` at the end of a cell will see a drawing followed by `'None'`. I think it's still easier to keep existing functionality and encourage people to type `display(qc.draw())` for these cases.

2020-11-09 11:49 UTC, mtreinish requested changes
I agree with @frankharkins here, we don't want to change the return type that will break user expectations for using draw(). I think having this be something we document for users to manually call in the jupyter context makes more sense.

2020-11-09 11:49 UTC, mtreinish commented on qiskit/tools/jupyter/__init__.py
> -from .monospace import MonospacedOutput
This should be deprecated before being removed. We also just added this last release it's a pretty bad user experience to say "hey, here's a new thing you can use to adjust the text drawer output" Then 2-3 months later "that new thing is going away"

2020-11-09 11:49 UTC, mtreinish commented on qiskit/circuit/quantumcircuit.py
> +        return str(circuit_drawer(self, output='text'))
This change is pointing to why this is not a good idea. We don't want to change the return type based on the environment you run in.

2020-11-09 11:49 UTC, mtreinish commented on qiskit/circuit/quantumcircuit.py
> +            return draw
If you were making this change why only on the draw method and not circuit_drawer itself?

2020-11-09 20:41 UTC, 1ucian0 commented
> I agree with @frankharkins here, we don't want to change the return type that will break user expectations for using draw().

Yeap... I agree. What about a `qc.display(...)`

2020-12-14 08:25 UTC, 1ucian0 commented
The right way to solve this is by calling `display` (by default in the jupyter notebook scope). 
```python
for circuit in circuits:
     display(circuit.draw(...))
```

2020-12-14 08:25 UTC, closed without merging