Fix timeline drawer measurement visualization
Qiskit/qiskit-terra pull request #5388
Opened 2020-11-12 09:24 UTC by nkanazawa1989

### Summary
fix #5361 

### Details and comments
Fix bit link visualization. Currently the drawer tries to visualize the bit link between qreg and creg even the creg is disabled. This causes an error because the coordinate of the creg is not initialized. In this PR, visible check is moved to correct place so that the link is also disabled. Unittests are also updated.

Box position bug of cregs is not fixed with this PR.

2020-11-12 12:54 UTC, taalexander requested changes
The warning is being triggered in docs building.

2020-11-12 12:54 UTC, taalexander commented on qiskit/visualization/timeline/interface.py
> +        warnings.warn('Start time of measure instruction on Clbits is not correctly parsed. '
```suggestion
        warnings.warn('Start time of the measure instruction on Clbits is not correctly parsed. '
```

2020-11-13 01:52 UTC, nkanazawa1989 commented
Is there any good way of avoiding this? We can add this warning but current creg output may confuse the users (because measurement on creg always starts from wrong position because creg doesn't have time information).

2020-11-13 12:20 UTC, taalexander commented
> Is there any good way of avoiding this? We can remove this warning but current creg output may confuse the users (because measurement on creg always starts from wrong position because creg doesn't have time information). Another option is removing debugging stylesheet from docstring, but I want to keep this.

Why is there a warning being emitted into the documentation?

2020-11-15 15:34 UTC, nkanazawa1989 commented
Because in the api docs I showed appearance of timeline images with three different preset stylesheets, namely `IQXSimple`, `IQXStandard`, `IQXDebugging`. Currently `show_clbits=True` generates a wrong image but `IQXDebugging` style should show whatever the drawer can according to its stylesheet policy. We should fix this bug at some point but I need more discussion.

2020-11-30 22:05 UTC, taalexander commented
I think right now it will be required to remove whatever is causing the warning in the documentation.

2021-01-26 01:46 UTC, nkanazawa1989 commented
close because this is addressed in #5662

2021-01-26 01:46 UTC, nkanazawa1989 commented
close because this is addressed in #5662

2021-01-26 01:46 UTC, closed without merging