Durations populated from calibrations
Qiskit/qiskit-terra pull request #5562
Opened 2020-12-28 16:58 UTC by lcapelluto

### Summary
Circuits with custom gate calibrations can now be scheduled with the
transpiler without explicitly providing the durations of each circuit
calibration.

### Details and comments

2021-01-04 05:46 UTC, itoko requested changes
Thank you for taking on this fix.

It seems to revert the spec change introduced in #5164 unintentionally.
According to #5164, `backend_durations` should be "overwritten" by `inst_durations` rather than "updated" as done in this PR.
I think, for `cal_durations`, updating would be more suitable than overwriting since cal gates are not args in transpile(), though.

2021-01-04 05:46 UTC, itoko commented on qiskit/compiler/transpile.py
> +                                             circuits, num_circuits)
I think we can replace `num_circuits` with `circuits`.

2021-01-04 05:46 UTC, itoko commented on qiskit/compiler/transpile.py
> +    for i in range(num_circuits):
We can now iterate over `circuits` instead of `num_circuits`.

2021-01-04 15:59 UTC, lcapelluto commented
Great points! I've updated

2021-01-05 03:03 UTC, itoko approved these changes
LGTM. Thanks!

2021-01-05 15:30 UTC, merged