Improved Clifford synthesis method
Qiskit/qiskit-terra pull request #5779
Opened 2021-02-03 09:28 UTC by ShellyGarion

### Summary
Add an improved Clifford synthesis method based on Bravyi et. al. greedy Clifford compiler.

### Details and comments

2021-02-03 11:07 UTC, ShellyGarion commented
@chriseclectic - the PR is ready for review - thanks!

2021-02-03 17:05 UTC, chriseclectic requested changes
Looks good, I just have a couple of suggestions for documentation

2021-02-03 17:05 UTC, chriseclectic commented on qiskit/quantum_info/synthesis/clifford_decompose.py
> +           [[True, False], [True, True]]]  # ['XY', 'XZ', 'YX', 'YZ', 'ZX', 'ZY']
Nit: you could comment the pauli on each line

2021-02-04 07:23 UTC, ShellyGarion commented on qiskit/quantum_info/synthesis/clifford_decompose.py
> +           *Clifford Circuit Optimization with Templates and Symbolic Pauli Gates*
there is no link yet.

2021-02-11 14:03 UTC, chriseclectic reviewed
Could more minor doc changes

2021-02-11 14:03 UTC, chriseclectic commented on qiskit/quantum_info/synthesis/clifford_decompose.py
> +        method (str): a synthesis method ('AG' or 'greedy')
```suggestion
        method (str): Optional, a synthesis method ('AG' or 'greedy'). If set this overrides optimal decomposition for N <=3 qubits. 
```

2021-02-11 14:03 UTC, chriseclectic commented on qiskit/quantum_info/synthesis/clifford_decompose.py
> +    which yields better CX cost compared to [2].
```suggestion
    which typically yields better CX cost compared to the AG method [2].
```

2021-02-12 14:42 UTC, ajavadia commented
can you add a reno releasenote please

2021-02-16 19:45 UTC, 1ucian0 commented on qiskit/quantum_info/synthesis/clifford_decompose.py
> +# (C) Copyright IBM 2017, 2020, 2021
```suggestion
# (C) Copyright IBM 2017, 2021
```

2021-03-04 22:09 UTC, chriseclectic approved these changes

2021-03-04 22:10 UTC, chriseclectic reviewed
LGTM, just needs a release note

2021-03-05 06:08 UTC, ShellyGarion commented
release notes are included: 
https://github.com/Qiskit/qiskit-terra/pull/5779/files#diff-09528904c5b6d193ec7eef03986f8ef40e5de9f37ba13164bcb1203e32b664a2

2021-03-05 14:47 UTC, merged