Add option to 1q euler decomposer for disabling unitary check
Qiskit/qiskit-terra pull request #5928
Opened 2021-02-27 20:07 UTC by mtreinish

### Summary

Previously when running the `OneQubitEulerDecomposer` the first step
it would perform is a check that the input matrix is a 1 qubit unitary.
However, in situations when we're explicitly generating a unitary matrix
and know the input we're passing is unitary there is no need to run this
check and it adds unnecessary overhead to the process. This commit adds a
new kwarg, check_unitary, to the __call__ method on the
`OneQubitEulerDecomposer` which when set to False will skip the unitary
check to avoid this overhead. The flag is then set
when the decomposer is called from the `Optimize1qGatesDecomposition`,
`UnitarySynthesis` passes, and `TwoQubitBasisDecomposer` to avoid the
overhead when we know the input is unitary.

### Details and comments

This depends on #5926

2021-03-04 22:11 UTC, levbishop requested changes
The idea of having a way to bypass consistency checks internally makes sense to me, but I prefer a different API for this kind of thing:

1. Instead of a user-visible flag, can we have an internal `_decompose()` method that skips the checks, and have the user-visible `__call__` do the checks and then go to `_decompose` for the (dangerous) implementation
2. For the internal API can we have the implementation work only with ndarray, and push the `to_operator`, `to_matrix`, `np.asarray` stuff for the user-facing friendly API (this should give a small additional perf boost)

2021-03-05 15:07 UTC, mtreinish commented
> The idea of having a way to bypass consistency checks internally makes sense to me, but I prefer a different API for this kind of thing:
> 
>     1. Instead of a user-visible flag, can we have an internal `_decompose()` method that skips the checks, and have the user-visible `__call__` do the checks and then go to `_decompose` for the (dangerous) implementation
> 
>     2. For the internal API can we have the implementation work only with ndarray, and push the `to_operator`, `to_matrix`, `np.asarray` stuff for the user-facing friendly API (this should give a small additional perf boost)

Yeah, that's a good idea and a pattern more consistent with the rest of qiskit too. I've pivoted to use the private method instead of the kwarg in: https://github.com/Qiskit/qiskit-terra/pull/5928/commits/9a2711b13f7fe23577f8f1b0952397a9aab3238a

2021-03-05 17:38 UTC, levbishop approved these changes
LGTM. If its not too much trouble, be nice to post perf numbers before/after to get a sense of how much this kind of thing matters - If this makes a big difference I'll fold the analog for `TwoQubitBasisDecomposer` into my PR #5827 changes

2021-03-05 18:23 UTC, mtreinish commented
Running the same script as I did in: https://github.com/Qiskit/qiskit-terra/pull/5926#issuecomment-791005813 the results for me locally were:

| version | time (in sec) |
| --- | --- |
| master | 22.62060546875 |
| #5928 (this PR) |  15.05669116973877 |

2021-03-05 18:39 UTC, merged