[WIP]  Add name argument in builder.play
Qiskit/qiskit-terra pull request #5935
Opened 2021-03-01 19:22 UTC by peendebak

### Summary

Add `name` argument to `qiskit.pulse.builder` the argument is passed to the underlying call to `instructions.Play`

### Details and comments

Default for the `name` argument is set to `None`, which is the same as for the `instructions.Play`

2021-03-01 19:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=5935) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=5935) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=5935) it.</sub>

2021-03-02 13:09 UTC, taalexander commented
Hello @peendebak, I was wondering if it would be possible to add this field for all similar instructions, eg., `set_phase`, `set_frequency`, `acquire`, etc.? In general, the `name` field is not often used for instructions outside of labeling metadata for visualization. The most important `name` is for the `Pulse` type for visualization.

2021-03-02 14:19 UTC, peendebak commented
@taalexander I added the `name` argument to several more methods. The `acquire` I skipped because the name can already be passed via the `metadata`

I also skipped the various context manager methods, e.g.
```
@contextmanager
def frequency_offset(frequency: float, ...
```

2021-03-03 20:20 UTC, taalexander requested changes
Almost there, just a couple small changes please and thank you 😄 .

2021-03-03 20:20 UTC, taalexander commented on qiskit/pulse/builder.py
> +            pulse.shift_phase(math.pi, d0, name='pi phase-shift')
I don't think we need to include this in the examples. In general, the `name` feature for instructions is not often used and the documentation mentions it.

2021-03-03 20:20 UTC, taalexander commented on test/python/pulse/test_builder.py
> +    def test_play_name_argument(self):
Would you mind adding a quick test of `name` setting to every `test_<inst>` test? I would really appreciate this.

2021-03-04 14:46 UTC, taalexander approved these changes
Looks great pending CI passing.

2021-03-08 13:15 UTC, taalexander approved these changes
Thank you very much for your contribution @eendebakpt, it is much appreciated 🥇 .

2021-03-08 17:17 UTC, merged