[WIP] Single bit conditioning support for registerless circuits
Qiskit/qiskit-terra pull request #6244
Opened 2021-04-16 12:04 UTC by TharrmashasthaPV

### Summary

This PR enables single bit conditioning of gates and instructions in registerless circuits. Work in progress

### Details and comments

This PR is an extension of #6018 to support single bit conditioning in registerless circuits. It is refactored over #6018 . Tests are yet to be added.

2021-04-23 21:50 UTC, kdk commented on qiskit/circuit/instructionset.py
> +        self.cregs = cregs
After talking with @1ucian0 , I think this is the right way of supporting `c_if(int, val)` right now. Can you add a comment here explaining why `cregs` is needed? (Also, maybe consider renaming as `circuit_cregs` or similar.)

2021-09-01 17:27 UTC, enavarro51 requested changes
It would be good to have a type/description here for `circuit_clbits`. Otherwise, looks good.

2021-09-04 16:40 UTC, enavarro51 approved these changes
LGTM. Thanks.

2021-09-06 15:09 UTC, 1ucian0 approved these changes
Thanks! once the single bit conditioning is fully supported, do you mind writing a release note with some details and examples?

2021-09-06 17:06 UTC, merged