Remove deprecation for pulse instruction parameter method
Qiskit/qiskit-terra pull request #6277
Opened 2021-04-21 17:08 UTC by nkanazawa1989

### Summary
The parameter manager (in PR #5854) deprecated the instruction-level management of parameters to realize light-weight instruction object, i.e.

```python
inst = Play(Gaussian(**params), d0)
inst.parameters  # deprecated
```

However this method is still needed for writing calibration code (thanks @eggerdj !). This PR removes deprecation warnings and add new logic to get the parameter set without initializing parameter table in the constructor.

### Details and comments
No unittest is added by this PR, because there are tests for `.parameters` method in `test/python/pulse/test_parameters.py`. These tests were not removed by #5854 for backward compatibility thus they should be still valid.

2021-04-21 17:14 UTC, mtreinish commented
Can you add a release note here? Probably an `other` note saying this isn't deprecated anymore. Since IIRC there was release note about this deprecation, we should document we're reversing that and it's not deprecated anymore and will continue to be supported.

2021-04-22 03:21 UTC, nkanazawa1989 commented
Thanks @mtreinish for catching this. Yes, deprecation node was added to 0.17 release. Reno is added.

2021-04-22 18:46 UTC, eggerdj approved these changes
LGTM.

2021-04-23 20:34 UTC, 1ucian0 commented on qiskit/pulse/instructions/play.py
> +            for ch_param in self.channel.parameters:
It seems that the tests need to be extended with parametrised channels:  https://coveralls.io/builds/39061954/source?filename=qiskit%2Fpulse%2Finstructions%2Fplay.py#L105

2021-04-23 20:35 UTC, 1ucian0 requested changes
Not fully sure, but maybe a new test is needed to cover the added code.

2021-04-26 01:27 UTC, nkanazawa1989 commented
Thanks @1ucian0 for catching this. Though these functionalities have been existing, it seems like we didn't have specific test for them. I added new test for play instruction paramters.

2021-04-26 19:30 UTC, 1ucian0 approved these changes
Thanks!

2021-04-26 19:30 UTC, merged