Fix behavior of instmap.add when partial function is specified
Qiskit/qiskit-terra pull request #6292
Opened 2021-04-23 07:56 UTC by nkanazawa1989

### Summary
Fix #6278 

### Details and comments
See unittest for details

2021-04-23 20:23 UTC, taalexander commented
I don't think special-casing `partial` support is the right way to handle this. I wrote up a long response and posted it to #6278 the other day but it seems to not have been posted ☹️. The gist of the problem is that it seems [partial](https://docs.python.org/3/library/functools.html#functools.partial) rather than binding supplied arguments fully, it creates them as keyword arguments in the returned partial object.

```
>>> functools.partialmethod(<function callable_schedule2 at 0x7ff790b79040>, , amplitude=0.4)
```

```python
inspect.signature(partial(callable_schedule2, amplitude=.4))
```

```
>>> <Signature (f, *, amplitude=0.4)>
```

The signature above is clearly not supported by `InstructionScheduleMap` as it currently only supports functions with a fixed number of arguments. The solution in this PR special cases `partial` but this is a more general policy of how keyword arguments should be handled in the function. 

There are several options:
1. Treat them as required arguments for scheduling (current behavior)
2. Ignore them as arguments (easy fix may be undesirable)
3. Special case `partial` (this PR, possibly undesirable as we will run into this problem again with similar function signature situations. We should define our policy).
4. Treat them as args based on ordering (would be slightly more effort, but could be done by storing signature objects rather than just a tuple of args?).

Right now I lean towards require signature being args only as Qiskit circuits/gates do not support variadic arguments. However, I am open to others' inputs.

2021-04-24 20:13 UTC, peendebak commented
@taalexander You accidentality posted your comment to https://github.com/Qiskit/qiskit-terra/issues/5951. 

I can see that 2., 3. or 4. might have some complications in actual implementation. If you decide to stick with 1., then perhaps document this and offer some method to update the signature of a `partial`. E.g., 
```
inspect.signature(partial(callable_schedule2, amplitude=.4))
>>> <Signature (f, *, amplitude=0.4)>
inspect.signature(only_args_signature(partial(callable_schedule2, amplitude=.4)))
>>> <Signature (f )>
```
I could not easily find an option for such a `only_args_signature`

2021-04-24 22:51 UTC, taalexander commented
> @taalexander You accidentality posted your comment to https://github.com/Qiskit/qiskit-terra/issues/5951. 
> 
> I can see that 2., 3. or 4. might have some complications in actual implementation. If you decide to stick with 1., then perhaps document this and offer some method to update the signature of a `partial`. E.g., 
> ```
> inspect.signature(partial(callable_schedule2, amplitude=.4))
> >>> <Signature (f, *, amplitude=0.4)>
> inspect.signature(only_args_signature(partial(callable_schedule2, amplitude=.4)))
> >>> <Signature (f )>
> ```
> I could not easily find an option for such a `only_args_signature`

Thanks for tracking that down 😌. I agree, either a solution or documentation is necessary. I also couldn't find an easy way around this with `partial`.

2021-04-26 16:37 UTC, nkanazawa1989 commented
I see @taalexander 's point. I carefully investigated [inspect](https://docs.python.org/3/library/inspect.html) module and found that this module covers all of those complicated signatures. So I changed `.add` logic to internally generate `Signature` object for schedule sub-classes, and offloaded parameter management to this object.

2021-04-29 17:39 UTC, taalexander requested changes
This is excellent @nkanazawa1989, I really appreciate you diving into this and coming up with an overall better implementation and great solution 😄 . Just a few small changes requested.

2021-04-29 17:39 UTC, taalexander commented on qiskit/pulse/instruction_schedule_map.py
> +                              'Input `arguments` is just ignored.', UserWarning)
```suggestion
                              'Input `arguments` are ignored.', UserWarning)
```

2021-04-29 17:39 UTC, taalexander commented on qiskit/pulse/instruction_schedule_map.py
> +            raise PulseError('Supplied schedule must be one of the Schedule, ScheduleBlock and '
```suggestion
            raise PulseError('Supplied schedule must be one of the Schedule, ScheduleBlock or a '
```

2021-04-29 17:39 UTC, taalexander commented on releasenotes/notes/fix-instmap-add-partial-bind-604b74158e5a56e3.yaml
> +    `functools.partial` function is input.
```suggestion
    Fix argument parsing bug of :meth:`InstructionScheduleMap.add` when a
    `functools.partial` function is input.
```

2021-05-04 13:30 UTC, taalexander approved these changes

2021-05-04 17:51 UTC, merged