Added the class RZXCalibrationBuilderNoEcho
Qiskit/qiskit-terra pull request #6300
Opened 2021-04-26 14:19 UTC by catornow

### Summary

In this PR I added a new class called RZXCalibrationBuilderNoEcho. 

### Details and comments

The RZXCalibrationBuilderNoEcho is a variation of the RZXCalibrationBuilder as it creates calibrations for the cross-resonance pulses without inserting the echo pulses in the pulse schedule. This enables exposing the echo in the cross-resonance sequence as gates so that the transpiler can simplify them. 
The RZXCalibrationBuilderNoEcho only supports the hardware-native direction of the CX gate.

2021-04-28 13:13 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +                                        ControlChannel(control)]).instructions
This needs to be changed.

2021-04-29 11:58 UTC, eggerdj requested changes
This is looking good. Some minor suggestions.

2021-04-29 11:58 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +        Filters the Schedule instructions for a Gaussian square pulse on the ControlChannel.
```suggestion
        Looks for Gaussian square pulses applied to control channels.
        
```

2021-04-29 11:58 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +        Filters the Schedule instructions for a Gaussian square pulse on the DriveChannel.
```suggestion
        Looks for Gaussian square pulses applied to drive channels.
        
```

2021-04-29 11:58 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +                specified direction of the cx.
```suggestion
            QiskitError: If the control and target qubits cannot be identified, or the backend
                does not support a cx gate between the qubits, or the backend does not natively
                support the specified direction of the cx.
```

2021-04-29 11:58 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +            if isinstance(inst.channel, DriveChannel) and not isinstance(inst, ShiftPhase):
```suggestion
            if isinstance(inst.channel, DriveChannel) and isinstance(inst, Play):
```

2021-04-30 14:47 UTC, eggerdj submitted a review, later dismissed
LGTM

2021-05-03 14:47 UTC, lcapelluto requested changes
Please add tests:)

2021-05-06 18:18 UTC, eggerdj requested changes
Thanks for adding the test. Here are some comments to improve this.

2021-05-06 18:18 UTC, eggerdj commented on test/python/pulse/test_calibrationbuilder.py
> +        )
```suggestion
        self.assertTrue(isinstance(rzx_qc_instructions[0][1], Play))
        self.assertTrue(isinstance(rzx_qc_instructions[0][1].pulse, GaussianSquare))
        self.assertEqual(rzx_qc_instructions[1][1].channel, DriveChannel(1))
        self.assertTrue(isinstance(rzx_qc_instructions[1][1], Delay))
        self.assertEqual(rzx_qc_instructions[2][1].channel, ControlChannel(1))
        self.assertTrue(isinstance(rzx_qc_instructions[2][1], Play))
        self.assertTrue(isinstance(rzx_qc_instructions[2][1].pulse, GaussianSquare))
```

2021-05-06 18:18 UTC, eggerdj commented on test/python/pulse/test_calibrationbuilder.py
> +        self.inst_map = self.defaults.instruction_schedule_map
```suggestion
        self.inst_map = self. backend.defaults().instruction_schedule_map
```
Looks like you do not need the configuration and the defaults.

2021-05-06 18:18 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +            raise QiskitError("Target qubit is None.")
```suggestion
            raise QiskitError("Target qubit is None.")
            
        if control != qubits[0]:
            raise QiskitError("RZXCalibrationBuilderNoEcho only supports hardware-native RZX gates.")
```

2021-05-06 18:18 UTC, eggerdj commented on qiskit/transpiler/passes/scheduling/calibration_creators.py
> +            raise QiskitError("Reverse direction not supported.")
```suggestion
        return rzx_theta
```
looking at this it makes more sense to do the test earlier to fail faster in case of an error.

2021-05-22 06:35 UTC, merged