Fixissue5784
Qiskit/qiskit-terra pull request #6637
Opened 2021-06-24 17:40 UTC by TheGupta2012

### Summary
Fixes issue #5784

### Details and comments
This issue was present in the `latex`, `text` and `mpl` drawers in the visualization library. Primarily added checks for the **size of the circuits** that were being passed in the drawers. The singleton registers, now, do not contain indices as was mentioned in the original issue.

Here are some screenshots of the expected results - 

```
from qiskit import * 
q2 = QuantumCircuit(3,2)
q  = QuantumCircuit(1)
q.h(0)
q.measure_all()
q2.x([0,1])
q2.cx(0,2)
q2.measure(0,1)

```

`q.draw(output='mpl',cregbundle=False,filename = "mpl_circ_1.JPG")`
`q.draw(output='mpl',filename = 'mpl_circ_2.JPG')`
`q2.draw(output='mpl',filename = 'mpl_circ_3.JPG')`

![mpl_circ_1](https://user-images.githubusercontent.com/57539040/123307661-62f86000-d540-11eb-97f3-f9c789f594f0.JPG)
![mpl_circ_2](https://user-images.githubusercontent.com/57539040/123307651-612e9c80-d540-11eb-94d7-0ef4eae63e59.JPG)
![mpl_circ_3](https://user-images.githubusercontent.com/57539040/123307658-625fc980-d540-11eb-93e8-4513f85daa25.JPG)

`q2.draw(output='text', filename = "text_circ_3.JPG")`
`q.draw(output='text',filename = "text_circ_1.JPG")`
`q.draw(output='text',cregbundle=False,filename = "text_circ_2.JPG")`

![text_circ_3](https://user-images.githubusercontent.com/57539040/123307877-a0f58400-d540-11eb-8223-0ac9d10be181.JPG)
![text_circ_1](https://user-images.githubusercontent.com/57539040/123307889-a521a180-d540-11eb-8fe0-35c0180e6c99.JPG)
![text_circ_2](https://user-images.githubusercontent.com/57539040/123307890-a5ba3800-d540-11eb-8053-dc3b4cd260a5.JPG)

`q.draw(output = 'latex', cregbundle = True)`
`q.draw(ouput = 'latex', cregbundle = False)`
`q2.draw(output = 'latex')`

![latex_issue_5784_1](https://user-images.githubusercontent.com/57539040/123306853-6d662a00-d53f-11eb-95e9-a5e228d45b61.png)
![latex_issue_5784_2](https://user-images.githubusercontent.com/57539040/123306915-7c4cdc80-d53f-11eb-9d03-890dbbbce2b1.png)
![latex_issue_5784_3](https://user-images.githubusercontent.com/57539040/123306919-7ce57300-d53f-11eb-8f25-733ef58ba717.png)

2021-07-07 19:22 UTC, TharrmashasthaPV requested changes
Thanks for working on this @TheGupta2012 . I believe I am having some troubles with the latex drawer. For instance, take the below code
```python
qc = QuantumCircuit(1,1)
qc.h(0)
qc.draw('latex_source')
```
This gives the following output
```latex
\documentclass[border=2px]{standalone}
        
\usepackage[braket, qm]{qcircuit}
\usepackage{graphicx}

\begin{document} 
\scalebox{1.0}{
\Qcircuit @C=1.0em @R=0.2em @!R { \\
	 	\nghost{\lstick{ {q} :  } & \lstick{\lstick{ {q} :  } & \gate{\mathrm{H}} & \qw & \qw\\ 
	 	\nghost{c:} & \lstick{c:} & \lstick{/_{_{1}}} \cw & \cw & \cw\\ 
\\ }}
\end{document}
```

See that there are some closing brackets missing and there is an `\lstick` element inside another `\lstick` element. This raises error in latex. Do you mind fixing them? I also have a few pointers that I have mentioned as comments.

2021-07-07 19:22 UTC, TharrmashasthaPV commented on qiskit/visualization/text.py
> +                            )
Do you think you it is possible to do something similar to what has been mentioned in comment at line 819?

2021-07-27 13:43 UTC, enavarro51 commented
@TheGupta2012 Just checking to see if you are still working on this. Thanks.

2021-08-04 16:25 UTC, javabster commented
@TheGupta2012  as we haven't heard from you I will reassign to @enavarro51 as he has asked to pick it up. If you would still like to work on it please reach out to Ed about continuing to work on it together 😄

2021-08-04 16:45 UTC, TheGupta2012 commented
> @TheGupta2012 as we haven't heard from you I will reassign to @enavarro51 as he has asked to pick it up. If you would still like to work on it please reach out to Ed about continuing to work on it together 😄

I am extremely sorry @javabster and @enavarro51, I haven't been able to take out the time for the past three weeks due to my college exams and tests. @enavarro51 you may continue to work on the fix and as soon as I am able to, I shall also contribute to the same.  
Again, really sorry for the delay..

2021-08-05 16:41 UTC, enavarro51 commented
@TheGupta2012 Thanks for the reply. No problem. We know everyone is busy with other things. I will start working on this in the next few days. I think I already have the items @TharrmashasthaPV reviewed above taken care of. The big task is fixing all the text drawer tests. There have been some changes merged into main that require some fixing. 

I'll just move along with it and if you have some time just let me know. I'll invite you as a collaborator on my repo when you're ready.

2022-01-19 08:46 UTC, closed without merging