Add the dark version of the IQX color scheme
Qiskit/qiskit-terra pull request #7186
Opened 2021-10-26 12:27 UTC by Cryoris

### Summary

Add the dark version of the IQX color scheme, as we don't yet support any "dark mode" circuit visualizations which would be very handy e.g. for dark presentations or similar.

### Details and comments

The color codes are taken from IQX and it looks like
![image](https://user-images.githubusercontent.com/5978796/138878079-ece8dbd0-cc42-4306-9514-4ffe14e9cf7f.png)

2021-12-02 09:52 UTC, Cryoris commented
I adapted the background color to the proper IQX one (`#262626`) and I think the PR is ready 👍🏻

2021-12-02 10:12 UTC, javabster approved these changes
LGTM 🚀

2021-12-02 10:34 UTC, javabster reviewed
Actually I think you'll need to add new reference images for the snapshot tests, to check 
you can run: https://mybinder.org/v2/gh/cryoris/qiskit-terra/iqx-dark?urlpath=apps/test/ipynb/mpl_tester.ipynb

2021-12-02 10:41 UTC, javabster requested changes

2021-12-02 10:41 UTC, javabster commented on test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
> +                self.circuit_drawer(circuit, style=style, filename="subfont.png")
This causes a naming clash as you're generating 'subfont.png' twice which causes the snapshot test to fail. I don't think it's strictly necessary to test the subfontsize with the new dark theme anyway but i guess it doesn't hurt

```suggestion
                self.circuit_drawer(circuit, style=style, filename="f"{name}_subfont.png"")
```

2021-12-02 12:45 UTC, javabster approved these changes
Snapshot tests in binder all pass now, thanks @Cryoris 😄

2021-12-10 18:39 UTC, jakelishman requested changes
I can't comment on the contrast/accessibility concerns because I really don't know much about them.  Did we decide that it was ok to maintain the white "+" in the cx gates in this theme, in contrast to the general IQX dark theme?

I also think we need to update the test in `qiskit/visualization/matplotlib.py:810` to include `"iqx-dark"`.  In the current form, this code:
```python
from qiskit.circuit import QuantumCircuit
from qiskit.circuit.library import SwapGate
from matplotlib import pyplot
circuit = QuantumCircuit(5)
circuit.append(SwapGate(), [3, 4], [])
circuit.append(SwapGate().control(3), [0, 1, 2, 3, 4], [])
circuit.draw("mpl", style="iqx-dark")
pyplot.show()
```
produces this image:

![Figure_1](https://user-images.githubusercontent.com/5968590/145624886-78891670-7c64-4ce6-810b-4bdaf3c88eb2.png)

but the multi-control swap gate should be blue as well.

2021-12-17 17:57 UTC, Cryoris commented
Thanks for catch @jakelishman! Also, I adjusted the color of the CX cross to be the same as the background:
![image](https://user-images.githubusercontent.com/5978796/146587608-0ff164c4-5580-41a0-98f3-86a1829e7a09.png)

The contrast question should be solved since we now have the same as IQX, so we're deferring to them 😉

2021-12-17 18:12 UTC, jakelishman approved these changes
Ace, thanks!

2021-12-17 19:48 UTC, merged