Update state_visualization.py
Qiskit/qiskit-terra pull request #7264
Opened 2021-11-14 02:17 UTC by sg495

### Summary

Closes #7263, introducing a use for the `figsize` argument of `plot_bloch_multivector`.

### Details and comments

Previously, the `figsize` argument of `plot_bloch_multivector` was not used by the visualisation, so it was impossible to change its size (e.g. to shrink it for single-qubit states). With this pull request, `figsize` can be used to set a size for individual Bloch ball sub-plots: if there are `num` qubits and `(w, h)` is passed to `figsize`, then the overall figure width is set to `num*w`, while its overall height is set to `h`.

2021-11-14 14:16 UTC, sg495 commented
I have made a few updates to the original pull request on `plot_bloch_multivector`.

Introduced a `font_size` kwarg to control font size in Bloch sphere plots:

![image](https://user-images.githubusercontent.com/13587235/141684814-eacf1967-e6ba-468e-97b4-e5d839b712da.png)

If custom `font_size` is used, title font size is adjusted accordingly:

![image](https://user-images.githubusercontent.com/13587235/141684881-c811b6fc-ad01-492e-bd57-cf08acf50a99.png)

Introduced a `title_font_size` and `title_pad` kwargs to control title font size and adjust padding:

![image](https://user-images.githubusercontent.com/13587235/141684905-297cc3f2-8c49-462a-8f38-5e4bbadb6adb.png)

2021-12-09 15:26 UTC, 1ucian0 commented on qiskit/visualization/state_visualization.py
> +        font_size (double): Font size.
```suggestion
        font_size (float): Font size.
```

2021-12-09 15:34 UTC, 1ucian0 requested changes
this looks good! Considering adding some testing in `test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py`

2021-12-09 15:34 UTC, 1ucian0 commented on qiskit/visualization/state_visualization.py
> +        title_pad (double): Padding for the title (suptitle `y` position is `y=1+title_pad/100`).
```suggestion
        font_size (float): Font size for the Bloch ball figures.
        title_font_size (float): Font size for the title.
        title_pad (float): Padding for the title (suptitle `y` position is `y=1+title_pad/100`).
```

2021-12-09 20:38 UTC, 1ucian0 commented on qiskit/visualization/bloch.py
> +        self, fig=None, axes=None, view=None, figsize=None, background=False, font_size=None
```suggestion
        self, fig=None, axes=None, view=None, figsize=None, background=False, font_size=20
```

2022-07-21 16:21 UTC, sg495 commented
> this looks good! Considering adding some testing in `test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py`
> 
> and a release note! Check the contributor guidelines https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md

I have included a release note and added a test for the new features, as requested 👍

2023-03-06 16:41 UTC, 1ucian0 requested changes
The test needs a reference file. Ill try to add it myself.

2023-03-06 16:41 UTC, 1ucian0 commented on test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py
> +            filename="bloch_multivector_figsize_improvements.png"
This reference file needs to exist in `test/ipynb/mpl/graph/references`.

2023-03-09 10:15 UTC, 1ucian0 commented on test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py
> +        circ.sxdg(2)
This is `NameError`, I think
```suggestion
        circuit.h(1)
        circuit.sxdg(2)
```

2023-03-09 11:16 UTC, 1ucian0 approved these changes
Thanks for the code and the patience! I fixed some things in the tests ([have a look](https://github.com/Qiskit/qiskit-terra/pull/7264/commits/356e98e57b2a819c94e61a20764f655bc643c87e) if curious). Next time, consider making smaller PRs, once per feature/bugfix, so they can be reviewed independently.

2023-03-09 11:22 UTC, 1ucian0 approved these changes
Thanks for the code and the patience! I fixed some things in the tests ([have a look](https://github.com/Qiskit/qiskit-terra/pull/7264/commits/356e98e57b2a819c94e61a20764f655bc643c87e) if curious). Next time, consider making smaller PRs, once per feature/bugfix, so they can be reviewed independently (and the changelog would get created more nicely)

2023-03-17 00:00 UTC, merged