Error printing empty PauliList #7359
Qiskit/qiskit-terra pull request #7712
Opened 2022-02-25 19:29 UTC by amyels

… Issue #7359

### Summary

Updated self.num_qubits to check if larger than 0 to avoid dividing by 0 

### Details and comments

Closes Issue #7359

2022-03-01 05:36 UTC, ikkoham submitted a review, later dismissed
Thank you very much. The change looks good. Could you add a test to pass empty PauliList to the `str()` function, and add release notes?

2022-03-01 05:49 UTC, ikkoham commented
@amyels You are a first time contributor, so if you are not sure about these additions, please feel free to ask here.

2022-07-25 20:37 UTC, jlapeyre commented
This looks great! I think it's ready for merge.

2022-07-25 20:37 UTC, jlapeyre submitted a review, later dismissed

2022-07-25 21:16 UTC, jlapeyre requested changes
EDITED: CI is blocking the merge because a file needs to be formatted by `black`.

[Here are instructions](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md#pull-request-checklist) giving one way to reformat with `black`. (In item number 1). In general, we need to reformat PRs with `black` after all changes have been made.

Otherwise, this looks great! The changes requested above by @ikkoham have been made.

2022-09-13 15:38 UTC, jlapeyre approved these changes

2022-09-14 16:44 UTC, mtreinish commented on releasenotes/notes/fix-empty-string-pauli-list-init-4d978fb0eaf1bc70.yaml
> +      pauli_list = PauliList.from_symplectic(x, z)
Try this:

```suggestion
    Fixed initialization of empty symplectic matrix in :meth:'PauliList.from_symplectic' in :class:'.PauliList' class
    For example::

        from qiskit.quantum_info.operators import PauliList

        x = np.array([], dtype=bool).reshape((1,0))
        z = np.array([], dtype=bool).reshape((1,0))
        pauli_list = PauliList.from_symplectic(x, z)
```

2022-09-16 13:55 UTC, mtreinish approved these changes

2022-09-16 16:50 UTC, merged