fix marginal_counts (which failed on pulse backend) (issue #6430)
Qiskit/qiskit-terra pull request #8099
Opened 2022-05-22 03:08 UTC by chetmurthy

[this is code copied from @rithikaadiga 's branch, but it's so small I just copied it, b/c didn't want to deal with applying all the 500+ changes since in the main trunk.]

When marginal_counts is passed a result that has ExperimentResults in it with headers that lack creg_sizes instance-variables, it just skips the "_adjust_creg_sizes" updating logic.

The test "test_result.py" is modified (by introducing a new test-class that subclasses the existing test) so that all the tests are run with versions of Result that have that field removed.  Again: there's a test there.  So subclass it, and in the subclass, during generation of Result-objects, remove the creg_sizes field.  Then all the tests will run (in the subclass).

### Summary

### Details and comments

2022-05-22 03:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8099) before we can accept your contribution.<br/><hr/>**Chet Murthy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=8099) it.</sub>

2022-05-22 03:10 UTC, chetmurthy commented
Re: CLA, this happened with my PR for qiskit-machine-learning; I'm not sure why it doesn't recognize me as being a Github user (I mean, I'm logged-into Github, after all).  Sigh.

2022-05-22 10:12 UTC, 1ucian0 commented
Hi @chetmurthy, thanks a lot for the PR! 

It's tradition to include the author you copied code from [as `Co-authored-by`](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). Do you mind amend your commit message with it?

2022-05-22 10:14 UTC, 1ucian0 commented on qiskit/result/utils.py
> +                    experiment_result.header.creg_sizes = _adjust_creg_sizes(csize, indices)
```suggestion
                csize = getattr(experiment_result.header, "creg_sizes")
                if (csize is not None):
                    experiment_result.header.creg_sizes = _adjust_creg_sizes(csize, indices)
```

2022-05-22 10:23 UTC, 1ucian0 requested changes
checkout how we usually refer to code elements in the release notes.

2022-05-22 10:23 UTC, 1ucian0 commented on releasenotes/fix-marginal_counts-on-pulse-backend.yaml
> +    The function qiskit.result.marginal_counts(), when passed a Result from a
```suggestion
    The method :meth:`qiskit.result.marginal_counts`, when passed a :class"`.Result` from a
```

2022-05-22 10:23 UTC, 1ucian0 commented on releasenotes/fix-marginal_counts-on-pulse-backend.yaml
> +    pulse backend, would fail, b/c: such a result contains an array of
```suggestion
    pulse backend, would fail, because it contains an array of
```

2022-05-22 18:22 UTC, chetmurthy commented
> Hi @chetmurthy, thanks a lot for the PR!
> 
> It's tradition to include the author you copied code from [as `Co-authored-by`](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). Do you mind amend your commit message with it?

I can't modify the original commit without redoing the entire branch, so I added to co-authored-by to the PR description.  Will that work?

2022-05-24 18:59 UTC, chetmurthy commented
Luciano, I think I resolved everything, yes?  Just checking.

2022-05-31 12:51 UTC, 1ucian0 commented on releasenotes/fix-marginal_counts-on-pulse-backend.yaml
> +    The method :meth:`qiskit.result.marginal_counts`, when passed a :class"`.Result` from a
```suggestion
    The method :meth:`qiskit.result.marginal_counts`, when passed a :class:`.Result` from a
```

2022-05-31 13:16 UTC, 1ucian0 commented on test/python/result/test_result.py
> +        return rv
I think this test is a bit artificial on one side, and covers too much on the other one.

2022-05-31 13:40 UTC, 1ucian0 requested changes
I'm not fully sure about the testing. Have a look to my suggestion if that makes sense to you.

2022-05-31 13:40 UTC, 1ucian0 commented on test/python/result/test_result.py
> +        return rv
Here is my suggestion, closer to the original issue.

```suggestion
    def test_marginal_counts_no_cregs(self):
        """Test that marginal_counts without cregs See qiskit-terra/6430."""
        raw_counts_1 = {"0x0": 4, "0x1": 7, "0x2": 10, "0x6": 5, "0x9": 11, "0xD": 9, "0x12": 8}
        data_1 = models.ExperimentResultData(counts=dict(**raw_counts_1))
        exp_result_header_1 = QobjExperimentHeader(memory_slots=5)
        exp_result_1 = models.ExperimentResult(
            shots=54, success=True, data=data_1, header=exp_result_header_1
        )

        result = Result(results=[exp_result_1], **self.base_result_args)

        marginal_counts_result = marginal_counts(result, indices=[0])
```

2022-06-01 08:09 UTC, 1ucian0 commented on test/python/result/test_result.py
> +        _ = marginal_counts(result, indices=[0])
once the result is computed, asserting it is relatively cheap. You would check that also works-as-expected, in addition to it-works.
```suggestion
        _ = marginal_counts(result, indices=[0])
        marginal_counts_result = marginal_counts(result, indices=[0])
        self.assertEqual(marginal_counts_result.get_counts(), {"0": 27, "1": 27})
```

2022-06-07 10:04 UTC, 1ucian0 approved these changes
LGTM, thanks a lot for your work!

2022-06-07 11:30 UTC, merged