Add wire_order option to 3 circuit drawers
Qiskit/qiskit-terra pull request #8173
Opened 2022-06-13 21:20 UTC by enavarro51

### Summary

Fixes #8063

### Details and comments

This PR adds the `wire_order` kwarg to `circuit_drawer()` and `QuantumCircuit.draw()`. It's entered as a list of bits, e.g.,
```
qr = QuantumRegister(4, "q")
cr = ClassicalRegister(4, "c")
cr2 = ClassicalRegister(2, "ca")
circuit = QuantumCircuit(qr, cr, cr2)
circuit.h(0)
circuit.h(3)
circuit.x(1)
circuit.x(3).c_if(cr, 10)
circuit.draw('mpl', cregbundle=False, wire_order=[2, 1, 3, 0, 6, 8, 9, 5, 4, 7])
```
![image](https://user-images.githubusercontent.com/16268251/173444082-060b285e-049d-42fe-bbe0-a59322c2b738.png)

The `wire_order` list must contain an entry for every bit, and the bits are numbered from 0 starting with the first qubit and continuing through the qubits and clbits.

The `reverse_bits` option works as it did before, but it now uses the same code that `wire_order` uses.

2022-07-10 14:01 UTC, 1ucian0 requested changes
Looks good, thanks!

Some comments here and there. Also, considerting extending the tests for checking the warnings and exceptions discussed in https://github.com/Qiskit/qiskit-terra/issues/8063#issuecomment-1141991937

2022-07-11 22:48 UTC, enavarro51 commented on qiskit/visualization/utils.py
> +def get_condition_label_val(condition, circuit, cregbundle):
Done in https://github.com/Qiskit/qiskit-terra/pull/8173/commits/a68cef77321b09ed37f93bba31aa03d6547ec8f8.

2022-07-11 22:49 UTC, enavarro51 commented on qiskit/visualization/circuit_visualization.py
> +        wire_order (list): optional. A list of integers used to reorder the display
Done in https://github.com/Qiskit/qiskit-terra/pull/8173/commits/a68cef77321b09ed37f93bba31aa03d6547ec8f8.

2022-07-12 15:41 UTC, 1ucian0 approved these changes
Thanks!

2022-07-12 17:11 UTC, merged