#5275 Template library [unitaryhack]
Qiskit/qiskit-terra pull request #8191
Opened 2022-06-16 19:25 UTC by mgg39

### Summary
Proposed template library, that Closes #5275 .

### Details and comments
I am currently actively working on this, please let me know if it requires reformatting.

2022-06-16 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Qiskit/qiskit?pullRequest=8191) <br/>All committers have signed the CLA.

2022-06-16 20:15 UTC, mgg39 commented
all templates have now been added to the library

2022-06-17 16:40 UTC, mgg39 commented
please let me know if there is a need for any additional commits or changes to the current proposal :)

2022-06-17 19:42 UTC, javabster commented
hi @mgg39 it looks like you have some linting issues, you should be able to fix these by running `tox -eblack`

2022-06-17 20:34 UTC, javabster reviewed
Thanks for working on this @mgg39!

2022-06-17 20:34 UTC, javabster commented on qiskit/circuit/library/template_library
> +# This code is part of Qiskit.
also the naming convention should match the other template library file. so either both should be `templates` or `template` not one of each :)

2022-06-17 20:49 UTC, mgg39 commented on qiskit/circuit/library/template_library
> +# This code is part of Qiskit.
Hi! Thank will change both of those

2022-06-17 21:05 UTC, mgg39 commented
Hi @javabster ! Thank you so much for your help! I changed the ran tox -eblack, added the .py extension, and eliminated the s from templates (hopefully everywhere in the files) . Hopefully there won't be any issues now :)

2022-06-18 10:43 UTC, ShellyGarion commented
Thank you very much @mgg39 for your contribution!

A few comments:

- The templates (like other parts of the qiskit code) should have **tests**. Currently, the tests for the templates are here:
https://github.com/Qiskit/qiskit-terra/blob/main/test/python/circuit/test_templates.py
Now, this test should check the templates in the new Template Library.
However, there should be a minor correction: all the templates should be _equal_ to identity, except of the Clifford templates which should be _equivalent_ to identity (up to a global phase).

- Currently the picture of the circuit of the template appears as a comment in the code, but not in the documentation of the template. It should be moved in a way such that it will appear as part of the **documentation**.

2022-06-19 21:01 UTC, mgg39 commented
Hi @ShellyGarion !
I am quite new to test driven development. Could you give me some guidance on how the testing file should look like? I am unsure of where to start.
Also where exactly is the relevant documentation where I should add the pictures?

2022-06-20 06:11 UTC, ShellyGarion commented
Please see the contributing guidelines about tests, code style, documentation and release notes:
https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md

2022-06-28 14:03 UTC, mgg39 commented
> Thank you @1ucian0 , I am currently going through the testing materials to design the relevant tests. I agree that the pull request should probably stay in draft whilst I design these.

2022-11-01 06:14 UTC, 1ucian0 commented
Hi @mgg39, how is that going?

2022-11-07 09:55 UTC, mgg39 commented
> Hi @mgg39, how is that going?

Hi @1ucian0 , sorry completely forgot about this with the new semester. Will try to finalise it this week :) Thank you for your patience!

2022-11-21 19:33 UTC, mgg39 commented
hi! could I have some guidance of what elements might be missing still or breaking the checks?
Thank you in advance

2022-11-29 21:03 UTC, javabster commented
Hi @mgg39 it looks like you have some conflicts, try fixing those first and then let's see if theres any CI issues. Also if your work is ready for review you can covert it to a regular Pr instead of a draft one 😄

2022-12-16 18:13 UTC, mgg39 commented
hi! I believe the remaining conflict is associated with a slightly moved indentation at the end of " qiskit/circuit/__init__.py "

2023-01-05 10:58 UTC, javabster commented
hi @mgg39 I resolved the merge conflict but you'll probably need to run `make black` again to sort out the indentation issue

2023-02-23 10:15 UTC, 1ucian0 requested changes
hi @mgg39 It seems that, there still some black issues:
```
Running black, any errors reported can be fixed with 'tox -eblack'
would reformat qiskit/circuit/library/__init__.py
would reformat qiskit/circuit/library/standard_gates/templates.py
would reformat test/python/circuit/test_templates.py

Oh no! 💥 💔 💥
3 files would be reformatted, 1733 files would be left unchanged.
```

2023-03-03 16:32 UTC, mgg39 commented
hopefully they are resolved now!

2023-05-11 10:58 UTC, 1ucian0 commented on qiskit/circuit/library/__init__.py
>  and :class:`~qiskit.circuit.library.CCXGate` (Toffoli) gates.
This paragraph belongs to the `NCT` title. Maybe you can introduce your section after it?

2023-05-11 11:10 UTC, 1ucian0 commented on test/python/circuit/test_templates.py
I think https://github.com/Qiskit/qiskit-terra/issues/5275 expects something like `test/python/circuit/test_equivalence.py`, where templetes are test to be equivalent to idle circuits.

2023-05-14 18:48 UTC, mgg39 commented on test/python/circuit/test_templates.py
will look into this

2026-05-04 16:09 UTC, 1ucian0 commented
The branch `grageragarces:main` is not writable to fix the conflicts.  Closing in favor of https://github.com/Qiskit/qiskit/pull/16131

2026-05-04 16:11 UTC, closed without merging