Avoid direct-CXs in RZX calibration pass
Qiskit/qiskit-terra pull request #8276
Opened 2022-06-29 20:01 UTC by nkanazawa1989

### Summary

RZX calibration pass is implemented for CX with echoed cross resonance sequence. Recent IBM backends started to support another realization of CX with so called direct-CX. Generation of fractional gate for this calibration is not straightforward because dynamics on the target qubit is much more complicated. 

In this PR, passes are updated to avoid termination by errors. This is temporary solution, just not to crash the transpiler. We need some additional research for the technique to stretch the direct-CX pulses. It is expected that these passes are upgraded again with support for direct-CXs.

### Details and comments

In addition to error-avoid mechanism, some cleanup has done in this PR. The logic for error avoidance is very simple. I newly introduced `CalibrationNotAvailable` exception, which is raised when the pass encounters the direct-CX. This is caught by the base class `CalibrationBuilder` to ignore invalid calibrations.

2022-06-29 20:02 UTC, nkanazawa1989 commented on qiskit/transpiler/passes/calibration/pulse_gates.py
> +class PulseGates(CalibrationBuilder):
(for review) Just moved to new file. Nothing changed.

2022-06-29 20:03 UTC, nkanazawa1989 commented on qiskit/transpiler/passes/calibration/rzx_builders.py
> +class RZXCalibrationBuilder(CalibrationBuilder):
(for review) Moved to new file, with some cleanup for `get_calibration` method.

2022-06-29 20:04 UTC, nkanazawa1989 commented on qiskit/transpiler/passes/calibration/base_builder.py
> +class CalibrationBuilder(TransformationPass):
(for review) Moved to new file

2022-06-29 20:04 UTC, nkanazawa1989 commented on qiskit/transpiler/passes/calibration/base_builder.py
> +                    continue
(for review) This is updated.

2022-06-30 19:53 UTC, taalexander requested changes
LGTM, just some minor comments.

2022-06-30 19:53 UTC, taalexander commented on releasenotes/notes/upgrade_rzx_builder_skip_direct_cx-d0beff9b2b86ab8d.yaml
> +    Transpiler pass module :mod:`~qiskit.transpiler.passes.calibration` has been reorganized.
```suggestion
    The transpiler pass module :mod:`~qiskit.transpiler.passes.calibration` has been reorganized.
```

2022-07-01 01:02 UTC, nkanazawa1989 commented on qiskit/transpiler/passes/calibration/builders.py
> +# This pass will be deprecated.
Yes, deprecation warning will be added in next release and removed afterwards. TODO comment is written as a reminder.

2022-07-04 12:25 UTC, taalexander approved these changes

2022-07-04 16:32 UTC, merged