Update documentation for BaseEstimator and BaseSampler: issues #8517 and #8516
Qiskit/qiskit-terra pull request #8560
Opened 2022-08-16 19:35 UTC by sebastian-mair

- [no] I have added the tests to cover my changes.
- [yes] I have updated the documentation accordingly.
- [yes] I have read the CONTRIBUTING document.

Linked Issues: 
* https://github.com/Qiskit/qiskit-terra/issues/8516
* https://github.com/Qiskit/qiskit-terra/issues/8517

### Summary
I updated the sample usages for qiskit.primitives.BaseEstimator and qiskit.primitives.BaseSampler, as well as a brief adaptation  of the general description of the class usage.
The updated description matches the current implementation - the existing documentation described a deprecated case and was adapted.

### Details and comments
This is my first contribution to any open source project, so hello there ;)

2022-08-16 19:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8560) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-terra?pullRequest=8560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-terra?pullRequest=8560) it.</sub>

2022-08-17 08:04 UTC, HuangJunye commented
@sebastian-mair Thanks a lot for making this contribution. As this is your first time contributing in Qiskit Terra, please read the [Contributing to Qiskit page](https://qiskit.org/documentation/contributing_to_qiskit.html), especially the [PR checklist](https://qiskit.org/documentation/contributing_to_qiskit.html#pull-request-checklist).

2022-08-17 08:04 UTC, HuangJunye commented
@ikkoham Would you like to review this PR?

2022-08-25 12:20 UTC, ikkoham requested changes
Congratulation on your great first contribution to OSS!
Thanks to you the documentation is much better.

It almost looks good to me. I'd like to left some minor comments.

2022-09-05 17:10 UTC, sebastian-mair commented on qiskit/primitives/base_estimator.py
> +create a :class:`qiskit.primitives.PrimitiveJob`, via the
Thank you, I'll correct that.

2022-09-26 08:07 UTC, t-imamichi submitted a review, later dismissed

2022-09-26 08:13 UTC, ikkoham commented
@t-imamichi I'll update this PR according to my comments.

2022-09-26 12:45 UTC, ikkoham commented
I checked the generated documents.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/6814928/192279635-46be40d0-f633-4bd0-a78b-53cd0a3687d0.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/6814928/192279692-1548445a-ac2a-4c06-a136-4c80fb3db1b1.png">

2022-09-26 12:46 UTC, ikkoham approved these changes
LGTM. Thank you for your contribution to qiskit.

2022-09-26 12:52 UTC, t-imamichi approved these changes

2022-09-26 13:55 UTC, merged