Fix VQD callback not being used
Qiskit/qiskit-terra pull request #8576
Opened 2022-08-18 10:33 UTC by Anthony-Gandon

Fix #8575 
This small change consists in adding the following lines during the call of the energy_evaluation() in VQD. These lines were taken from the VQE algorithm.
```
if self._callback is not None:
    variance = np.real(expectation.compute_variance(sampled_expect_op))
    estimator_error = np.sqrt(variance / self.quantum_instance.run_config.shots)
    for i, param_set in enumerate(parameter_sets):
        self._eval_count += 1
        self._callback(self._eval_count, param_set, means[i], estimator_error[i], step)
else:
    self._eval_count += len(means)
```
The corresponding test is modified accordingly.
The callback also keeps track of the current step in the VQD algorithm.

2022-08-18 15:05 UTC, jlapeyre requested changes
LGTM.  I did have a small question.

2022-08-18 19:51 UTC, Anthony-Gandon commented on qiskit/algorithms/eigen_solvers/vqd.py
> +                Should have size k -1, the number of excited states.
Indeed. I changed it accordingly

2022-08-23 14:18 UTC, Cryoris approved these changes
LGTM thanks for the fix!

2022-08-23 20:58 UTC, woodsp-ibm approved these changes

2022-08-23 21:06 UTC, jlapeyre approved these changes
Thanks!

2022-08-24 20:29 UTC, merged